-- Schema for Skill Share application (MySQL)
-- Save this file and import it into XAMPP/MySQL (phpMyAdmin or mysql client)

CREATE DATABASE IF NOT EXISTS `skill_share` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE `skill_share`;

-- Users table
CREATE TABLE IF NOT EXISTS `users` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(50) NOT NULL UNIQUE,
  `password_hash` VARCHAR(255) NOT NULL,
  `full_name` VARCHAR(150) NOT NULL,
  `bio` TEXT DEFAULT NULL,
  `category` ENUM('java','python','c') NOT NULL DEFAULT 'python',
  `google_classroom` VARCHAR(255) DEFAULT NULL,
  `profile_image` VARCHAR(255) DEFAULT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Ratings table: people rate users
CREATE TABLE IF NOT EXISTS `ratings` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT UNSIGNED NOT NULL,
  `rater_id` INT UNSIGNED DEFAULT NULL,
  `rating` TINYINT UNSIGNED NOT NULL CHECK (rating BETWEEN 1 AND 5),
  `comment` TEXT DEFAULT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX (`user_id`),
  CONSTRAINT `fk_ratings_user` FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_ratings_rater` FOREIGN KEY (`rater_id`) REFERENCES `users`(`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Todos table: relational tasks per user
CREATE TABLE IF NOT EXISTS `todos` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT UNSIGNED NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `notes` TEXT DEFAULT NULL,
  `is_done` TINYINT(1) NOT NULL DEFAULT 0,
  `due_date` DATETIME DEFAULT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX (`user_id`),
  CONSTRAINT `fk_todos_user` FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- NOTE: No sample users are inserted by default. Use the web
-- registration form (register.php) to create accounts, or insert
-- manually using a password hash generated by PHP's password_hash().
-- Example SQL to create a user (replace <hash>):
-- INSERT INTO `users` (username, password_hash, full_name, bio, category, google_classroom)
-- VALUES ('alice', '<hash>', 'Alice Example', 'Demo instructor for Python', 'python', 'https://classroom.google.com');
-- To generate <hash> from a PHP CLI (XAMPP), run:
-- C:\xampp\php\php.exe -r "echo password_hash('secret123', PASSWORD_DEFAULT) . PHP_EOL;"

